name: "publish"

on:
  push:
    branches:
      - main

jobs:
  publish:
    # name: publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.2
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        registry-url: https://registry.npmjs.org
        scope: "@tramdhan"
        # registry-url: https://npm.pkg.github.com
      # - run: yarn install
      # - run: npm publish
        - name: publish
          run: npm publish --access public
        working-directory: react-icons
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
          # NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
