name: "publish"

on:
  push:
    branches:
      - main

jobs:
  release:
    name: publish
    runs-on: ubuntu-latest
    steps:
        uses: actions/checkout@v2.4.2
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org
      - run: npm ci
      - run: npm test
      - name: publish
        run: npm publish --access public
        working-directory: my-package
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
